/**
 * gloocode-launch — tiny wrapper used by `~/.local/bin/gloocode` (the shim
 * generated by `install.sh` at the repo root).
 *
 * Why this exists:
 *
 *   bun resolves `tsconfig.json` from its working directory at startup.
 *   opencode's TUI source uses solid-js JSX and needs
 *   `packages/opencode/tsconfig.json` (`jsxImportSource: "@opentui/solid"`)
 *   for that JSX to compile correctly.
 *
 *   The shim therefore launches bun with `--cwd packages/opencode` so
 *   tsconfig is found. But we also want opencode's `process.cwd()` at
 *   runtime to be the user's *invocation* directory — so the opencode
 *   default tui command treats that as the workspace, not the opencode
 *   source tree itself.
 *
 *   This wrapper bridges the two: it runs after bun has finished loading
 *   tsconfig, then chdir's to the original invocation cwd before
 *   dynamically importing the real entry point. The dynamic import keeps
 *   opencode's source untouched and lets bun handle module resolution
 *   normally; the chdir flips `process.cwd()` so workspace detection
 *   and any cwd-relative path lookups inside opencode see the user's
 *   project, not packages/opencode.
 *
 *   The shim sets `GLOOCODE_ORIG_CWD` to the directory it was invoked
 *   from. Without that env var (e.g., direct invocation outside the
 *   shim), this wrapper is a transparent passthrough.
 */
const origCwd = process.env["GLOOCODE_ORIG_CWD"]
if (origCwd && origCwd.length > 0) {
  process.chdir(origCwd)
}

await import("../src/index.ts")
